---
title: "School Run l'Esculapi"
author: "Marc Deixt"
date: '`r Sys.Date()`'
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(tidygeocoder)
library(stringr)
library(leaflet)
library(leaflet.extras)
library(osmdata)
library(sf)
library(stplanr)
library(igraph)
library(dodgr)
library(units)
#library(ggmap)


## First, we clean the working memory

#rm(list = ls())


## Second, set working directory

setwd("~/Yandex.Disk/UOC/SIDE-PROJS/SHCOOLRUN/")
```

## Adreces
Llegim les adreces del csv


```{r}
df <- read.csv("Adreces.csv",stringsAsFactors = FALSE)
adresses <- df %>%
  filter(Codi.postal=="17130" && Municipi.de.residència=="L'Escala" ) %>%
 mutate(via = str_replace_all(Tipus.de.via, c("CR"="Carrer","AV" ="Avinguda", "PG"= "Passatge","PL"="Plaça","CM"="Camí") )) %>%
  select(c(Nom.via,Porta,Municipi.de.residència,Codi.postal)) %>%
  mutate(sep_1=",",.before=Municipi.de.residència)%>%
  mutate(sep_2=", Alt Empordà, Girona, ",.after=Municipi.de.residència)%>%
  unite(col="address",sep=" ") 
#AFEGIM la de l'escola

adresses <- adresses %>%
  add_row(address = "Carrer Teranyina 8, L'Escala, 17130")

```




## Geocoding

```{r eval=FALSE}


coordinates <- adresses %>%
  tidygeocoder::geocode(address,timeout= 5)
 saveRDS(coordinates,file="coordinates.Rda")

```

```{r}

coordinates <- readRDS("coordinates.Rda")
coordinates
```


```{r}

coordinates  <- 
  coordinates %>%
  filter(long>3.1)
  drop_na

escola <- coordinates[nrow(coordinates),]
coordinates <- coordinates[1:nrow(coordinates),]



```




```{r}
icon <- makeIcon(iconUrl="pupil_icon.png",iconWidth = 10,iconHeight = 10)
sc_icon <-  makeIcon(iconUrl="school-icon.png",iconWidth = 35,iconHeight = 35)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=coordinates$long, lat=coordinates$lat, popup=coordinates$address,icon=icon)%>%
  addMarkers(lng=escola$long, lat= escola$lat, icon = sc_icon)
m

```


Convert points to to SF object
```{r}

# Convert data frame to sf object
alumnes_sf <-  st_as_sf(x = coordinates, 
                        coords = c("long", "lat"),
                        crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")

escola_sf <- st_as_sf(x = escola, 
                        coords = c("long", "lat"),
                        crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
```


```{r}
escola_sf[1,"address"] <- "ESCOLA"
alumnes_i_escola <- rbind(alumnes_sf,escola_sf)
```




### Maybe explore the graph way. Download ways and points,nodes and vertices and find shortest path.


```{r}
available_tags("highway")
```



```{r}

#building the query
carrers_lescala <- getbb("L'Escala") %>%
       opq()  %>%
       add_osm_feature(key="highway",value = c("residential", "living_street",
                            "unclassified",
                            "service", "footway", "cycleway"
                  )) %>% #maybe filter and get only small streets?
  osmdata_sf()


```


```{r}

escola_sf_m_CRS <- st_transform(escola_sf, "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs")
r15 <- set_units(1.8, km)
esc_buffer <- st_buffer(escola_sf_m_CRS,r15)
escola_sf <- st_transform(escola_sf_m_CRS,crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
```


```{r fig.width=10,fig.height=10}
library(ggplot2)


ggplot() +
  geom_sf(data=esc_buffer, inherit.aes = FALSE,color="violet")+
  geom_sf(data = carrers_lescala$osm_lines,
          inherit.aes = FALSE,
          color = "gray") +
  geom_sf(data = alumnes_sf,inherit.aes = FALSE)+
  geom_sf(data = escola_sf,inherit.aes = FALSE,color="violet")


``` 













Transform or convert coordinates of simple feature

```{r}

carrers_sf <- carrers_lescala$osm_lines %>%
  st_transform(crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0") 
```



```{r}
# Create a matrix of touching streets
touching_streets <- st_touches(carrers_sf, sparse = FALSE)

```

Flipo que faci servir hclust per això. Mira-t'ho bé.

```{r}
# Merge all streets that touch each other converting all
highways_hclust <- hclust(as.dist(!touching_streets), method = "single")
# Cut the dendrogram at heigh 0.5 so that all touching 
  # streets stay in the same group
  highways_groups <- cutree(highways_hclust, h = 0.5)
```



```{r}
table(highways_groups)
```


```{r}
carrers_sf <- carrers_sf[highways_groups == 1, ]

```


```{r}
#library(purrr)
nearest_point <- alumnes_i_escola %>%
  mutate(
    index_of_nearest_feature = st_nearest_feature(., carrers_sf),
    nearest_feature = st_geometry(carrers_sf[index_of_nearest_feature,]),
    nearest_point = purrr::pmap(
      list(geometry, nearest_feature),
      ~ st_nearest_points(.x, .y) %>% st_cast("POINT") %>% magrittr::extract2(2)
    )
  ) %>%
  pull(nearest_point) %>%
  st_sfc(crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0") 

nearest_point
```



```{r}
alumnes_i_escola_nearest_points <- alumnes_i_escola %>% 
  st_drop_geometry() %>% 
  st_as_sf(., geometry = nearest_point)
alumnes_i_escola_nearest_points
```

```{r}
library(ggplot2)
ggplot() +
  geom_sf(data = carrers_sf$geom,
          inherit.aes = FALSE,
          color = "gray") +
  geom_sf(data = alumnes_i_escola_nearest_points,inherit.aes = FALSE)
```


```{r}
carrers_sf <-carrers_sf[,"name"]
rnet <- SpatialLinesNetwork(rnet_breakup_vertices(rnet = carrers_sf))

```


```{r}

nodes_origen <- stplanr::find_network_nodes(sln = rnet, x = coordinates$long, y = coordinates$lat)

node_desti <- stplanr::find_network_nodes(sln = rnet, x = escola$long, y = escola$lat)
```


```{r}

od_data = data.frame(start = nodes_origen, end = node_desti)

```

```{r}

rutes = sum_network_links(sln = rnet, routedata = od_data)
rutes <- drop_na(rutes)

ggplot() +
  geom_sf(data = rutes$geometry,
          inherit.aes = FALSE,
          color = "gray") +
  geom_sf(data = alumnes_i_escola_nearest_points,inherit.aes = FALSE)


```


```{r}
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addPolygons(data=rutes$geometry) %>%
  addMarkers(data = alumnes_i_escola_nearest_points, icon = icon) %>%
  addMarkers(lng=escola$long, lat= escola$lat, icon = sc_icon)

m

```



Busquem distàncies

```{r}

carrers_sf <- carrers_lescala$osm_lines %>%
  st_transform(crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0") 

graph <- weight_streetnet (carrers_sf)
head (graph)
graph_first_comp<- (graph[graph$component==1,])
grc <- dodgr_contract_graph (graph)
```


```{r}
verts <- dodgr_vertices (graph)
xy <- data.frame(x=coordinates$long,y=coordinates$lat)
pts <- match_pts_to_graph (verts, xy)
pts <- verts$id [pts]
d <- dodgr_dists (graph, from = pts[1:(length(pts)-1)],to =pts[length(pts)] )
summary(d)
```





```{r fig.width=7,fig.height=10,echo=FALSE,warning=FALSE}

#això és important, splantr ens conserva el SF a @sl$geom i ens crea un graf a @g. el mètode edge_betweenness és responsable d'assignar els pesos segons la coincidència.
ways_sln = SpatialLinesNetwork(rutes)
e = igraph::edge_betweenness(ways_sln@g)

ggplot() +
  geom_sf(data = carrers_sf$geom,
          inherit.aes = FALSE,
          color = "gray", alpha= 0.4) +
    geom_sf(data = ways_sln@sl$geometry,
          inherit.aes = FALSE,
          color = "violet",
          size=e / 6000) +
  geom_sf(data = alumnes_i_escola_nearest_points,inherit.aes = FALSE, alpha=0.2,size=0.5) +
  geom_sf(data=escola_sf, inherit.aes = FALSE, color="blue")
```















```{r}
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addPolygons(data=ways_sln@sl$geometry, weight= e / 2000, color ="black") %>%
  addMarkers(data = alumnes_i_escola_nearest_points, icon = icon) %>%
  addMarkers(lng=escola$long, lat= escola$lat, icon = sc_icon) %>%
  addFullscreenControl()

m

```
